-- MySQL Script generated by MySQL Workbench
-- Sat Dec 30 16:22:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baza` DEFAULT CHARACTER SET utf8 ;
USE `baza` ;

-- -----------------------------------------------------
-- Table `baza`.`aranzmani`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`aranzmani` (
  `id` INT(11) NOT NULL,
  `naziv` VARCHAR(45) NULL DEFAULT NULL,
  `cena` DOUBLE NULL DEFAULT NULL,
  `brojSlobodnihMesta` INT(11) NULL DEFAULT NULL,
  `brojMesta` INT(11) NULL DEFAULT NULL,
  `polaznaDestinacija` VARCHAR(45) NULL DEFAULT NULL,
  `vremePolaska` DATETIME NULL DEFAULT NULL,
  `dolaznaDestinacija` VARCHAR(45) NULL DEFAULT NULL,
  `vremeDolaska` DATETIME NULL DEFAULT NULL,
  `info` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baza`.`klijenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`klijenti` (
  `id` INT(11) NOT NULL,
  `ime` VARCHAR(45) NULL DEFAULT NULL,
  `prezime` VARCHAR(45) NULL DEFAULT NULL,
  `datumRodjenja` DATETIME NULL DEFAULT NULL,
  `brojTelefona` VARCHAR(45) NULL DEFAULT NULL,
  `emailAdresa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baza`.`rezervacije`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`rezervacije` (
  `id` INT(11) NOT NULL,
  `klijent_id` INT(11) NOT NULL,
  `aranzman_id` INT(11) NOT NULL,
  `vremeRezervacije` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ARANZ_idx` (`aranzman_id` ASC),
  INDEX `FK_KLIJ_idx` (`klijent_id` ASC),
  CONSTRAINT `FK_ARANZ`
    FOREIGN KEY (`aranzman_id`)
    REFERENCES `baza`.`aranzmani` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_KLIJ`
    FOREIGN KEY (`klijent_id`)
    REFERENCES `baza`.`klijenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
